name: OCR build and push ci

on:
  push:
    branches:
      - "main"
    paths:
      - "services/receipt-ocr/**"
      - ".github/workflows/build-ocr.yml"

env:
  AWS_REGION: ap-south-1
  IMAGE_NAME: lambda-receipt-ocr

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/receipt-ocr
          file: ./services/receipt-ocr/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:latest

      - name: Log out from AWS ECR
        run: docker logout
