name: API build and push ci

on:
  push:
    branches:
      - "main"
    paths:
      - "services/backend/**"
      - ".github/workflows/build-api.yml"

env:
  IMAGE_NAME: lambda-receipt-ocr

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}  # Updated secret key name
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}  # Updated secret key name
          aws-region: ap-south-1  # Change this to your AWS region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/backend
          file: ./services/backend/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/lambda-receipt-ocr:latest

      - name: Log out from AWS ECR
        run: docker logout
